env = Environment()

env['APP_TARGET'] = 'AssimpApp'
env['APP_SOURCES'] = ['AssimpApp.cpp']
env['ASSETS'] = ['seymour.dae', 'seymour.jpg']
env['DEBUG'] = 1

# Cinder-Assimp
_INCLUDES = [Dir('../src').abspath]

_SOURCES = ['AssimpLoader.cpp']
_SOURCES = [File('../src/' + s).abspath for s in _SOURCES]

_LIBS = ['libassimp.a']
if env['PLATFORM'] == 'darwin':
	_LIBS = [Dir('../lib/macosx/').abspath + '/' + s for s in _LIBS]
else:
	_LIBS = []

_LIBS = [File(s) for s in _LIBS]

env.Append(APP_SOURCES = _SOURCES)
env.Append(CPPPATH = _INCLUDES)
env.Append(LIBS = _LIBS)
# 

SConscript('../../../scons/SConscript', exports = 'env')

